---
title: Grammatical gender exploration
subtitle: 
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    number_sections: no
    toc: yes
---
  
******

```{r setup, include = F}
# load packages
library(knitr)
library(rmarkdown)
library(tidyverse)
library(langcog)
library(modelr)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F, cache = F)
```

Qs: 

* what to do with languages with common-neuter distinction, previously grouping them with gendered langs, but if you count them as none, efffet goes away

* redid things using residualized measure

```{r}
LANGUAGE_DF_PATH <- "/Users/mollylewis/Documents/research/Projects/1_in_progress/IATLANG/analyses/7_age_controls/by_language_df.csv"
LANGUAGE_DF_PATH_NEW <-  "/Users/mollylewis/Documents/research/Projects/1_in_progress/IATLANG/analyses/2_pretrained_w2v_models/embedding_IAT_v2/es_career_separate.csv"
GENDER_PATH <- "gender_grammar.csv"
```


```{r, fig.width = 8, fig.height = 8}
gender_data <- read_csv(GENDER_PATH) %>%
  select(language_code, language_name, wikipedia_grammar_type) %>%
  mutate(wikipedia_grammar_type2 = ifelse(wikipedia_grammar_type == "none",
                                          "No Gender", 
                                          "Gender")) %>%
    mutate(wikipedia_grammar_type3 = ifelse(wikipedia_grammar_type %in% c("none", "CN"),
                                          "No Gender", 
                                          "Gender")) %>%
    rename(wiki_language_code = language_code) 

language_df_new <- read_csv(LANGUAGE_DF_PATH_NEW) %>%
  rename(career_hand_new = sYXab,
         wiki_language_code = language_code) %>%
  select(wiki_language_code, career_hand_new)


language_df_with_ggi <- read_csv(LANGUAGE_DF_PATH) %>%
  select(wiki_language_code, es_behavioral_iat_resid_simple) %>%
  left_join(language_df_new) %>%
  left_join(gender_data, by = "wiki_language_code") %>%
  filter(!is.na(es_behavioral_iat_resid_simple)) 

```

Here CN counted as gendered
```{r}
language_df_with_ggi %>%
  ungroup() %>%
  mutate( wikipedia_grammar_type2 = fct_rev(wikipedia_grammar_type2)) %>%
  ggplot(aes(x = wikipedia_grammar_type2, 
             y = es_behavioral_iat_resid_simple,
             color = wikipedia_grammar_type2)) +
  geom_boxplot(outlier.alpha = 0) +
  scale_color_manual(values = c("blue", "red")) +
  geom_point(color = "black", alpha = .4,
             aes(x = wikipedia_grammar_type2),
             size = 2) +
  coord_flip() +
  theme_classic() +
  ggtitle("Behavioral IAT and Grammar Type") +
  ylab("Behavioral IAT Gender Bias\n (effect size)") +
  xlab("Grammar Type") +
  theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.y = element_text(angle = 90, hjust=0.5, size = 8))

mf <- filter(language_df_with_ggi %>% filter(wiki_language_code != "hi"),wikipedia_grammar_type2 == "Gender")
none <- filter(language_df_with_ggi %>% filter(wiki_language_code != "hu"),wikipedia_grammar_type2 == "No Gender")

t.test(mf$es_behavioral_iat_resid_simple, 
                       none$es_behavioral_iat_resid_simple, 
                       paired = F)
```
(t-test excludes outliers)


Here CN counted as not gendered
```{r}
language_df_with_ggi %>%
  ungroup() %>%
  mutate( wikipedia_grammar_type3 = fct_rev(wikipedia_grammar_type3)) %>%
  ggplot(aes(x = wikipedia_grammar_type3, 
             y = es_behavioral_iat_resid_simple,
             color = wikipedia_grammar_type3)) +
  geom_boxplot(outlier.alpha = 0) +
  scale_color_manual(values = c("blue", "red")) +
  geom_point(color = "black", alpha = .4,
             aes(x = wikipedia_grammar_type3),
             size = 2) +
  coord_flip() +
  theme_classic() +
  ggtitle("Behavioral IAT and Grammar Type") +
  ylab("Behavioral IAT Gender Bias\n (effect size)") +
  xlab("Grammar Type") +
  theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.y = element_text(angle = 90, hjust=0.5, size = 8))

mf <- filter(language_df_with_ggi %>% filter(wiki_language_code != "hi"),wikipedia_grammar_type3 == "Gender")
none <- filter(language_df_with_ggi %>% filter(wiki_language_code != "hu"),wikipedia_grammar_type3 == "No Gender")

t.test(mf$es_behavioral_iat_resid_simple, 
                       none$es_behavioral_iat_resid_simple, 
                       paired = F)
```

Here's a 4-way distinction
```{r} 
language_df_with_ggi %>%
  ungroup() %>%
  ggplot(aes(x = wikipedia_grammar_type, 
             y = es_behavioral_iat_resid_simple,
             color = wikipedia_grammar_type)) +
  geom_boxplot(outlier.alpha = 0) +
  geom_point(color = "black", alpha = .4,
             aes(x = wikipedia_grammar_type),
             size = 2) +
  coord_flip() +
  theme_classic() +
  ggtitle("Behavioral IAT and Grammar Type") +
  ylab("Behavioral IAT Gender Bias\n (effect size)") +
  xlab("Grammar Type") +
  theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.y = element_text(angle = 90, hjust=0.5, size = 8))
```