---
title: Comparing behavior vs. language
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    number_sections: no
    toc: yes
---
  
```{r setup, include = F}

# load packages
library(knitr)
library(rmarkdown)
library(tidyverse)
library(langcog)
library(stringr)
library(forcats)
library(broom)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F, cache = F)
```
Are the explicit measures correlated with language bias?

Read in behavior and language biases
```{r}
countries_langs <- read_csv("../../data/other/countries_lang.csv") %>%
  mutate(language_name = ifelse(language_name == "Spanish; Castilian", "Spanish", language_name),
         language_name = ifelse(language_name == "Dutch; Flemish", "Dutch", language_name))


IAT_behavior_measures <- read_csv("IAT_behavior_measures.csv") %>%
  left_join(countries_langs %>% select(country_name, language_name, language_code)) %>%
  filter(type %in% c("country_fam_male", 
             "country_career_male", 
             "career_importance", 
             "family_importance",
             "actual_duties")) %>%
  group_by(type, language_code, sex) %>%
  summarize(mean = mean(mean)) 

lang_bias <- read_csv("career_effect_sizes.csv")

lang_bias_google <- read_csv("google_translate/career_effect_sizes_google.csv",
                             col_names = c("language_code",   "test",  "test_name", "lang_bias")) %>%
  filter(language_code != "he", language_code != "zu", language_code != "th") 
#,language_code !=  "ha",language_code !=  "id",language_code !=  "zh")


d <- left_join(IAT_behavior_measures, lang_bias) %>%
  mutate_if(is.character, as.factor) %>%
  filter(!is.na(lang_bias))
```

There are `r length(unique(d$language_code))` languages represented here.


## Measures
### Behavior
```{r, fig.width = 5, height = 3}
ggplot(d, aes(x = mean)) +
  geom_histogram() +
  facet_wrap(~type, scales = "free_x")+
  theme_bw()
```

## Correlation between measures - Hand-translations

```{r,  fig.width = 10, fig.height = 2.5}
d %>%
  mutate(type2 = ifelse(type %in% c("country_gender_D_score_diff", "country_means_D_score", "country_gender_D_score"), "D-score", ifelse(type %in% c("country_RT_ratio", "country_RT_mean"), "RT", "explicit"))) %>%
ggplot( aes(x = mean, y = lang_bias, group = sex, color = sex, shape = type2)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_grid(.~type2 + type, scales = "free_x", drop = T) +
  theme_bw()
```


```{r, fig.width = 10}
d %>%
  group_by(type, sex) %>%
  do(tidy(cor.test(.$mean, .$lang_bias))) %>%
  arrange(p.value) %>%
  select(-parameter, -method, -alternative) %>%
  kable()
```

## Correlation between measures - Google-translations
```{r}
d <- left_join(IAT_behavior_measures, lang_bias_google) %>%
  mutate_if(is.character, as.factor) %>%
  filter(!is.na(lang_bias))

```

There are `r length(unique(d$language_code))` languages represented here.

```{r,  fig.width = 10, fig.height = 2.5}
d %>%
  mutate(type2 = ifelse(type %in% c("country_gender_D_score_diff", "country_means_D_score", "country_gender_D_score"), "D-score", ifelse(type %in% c("country_RT_ratio", "country_RT_mean"), "RT", "explicit"))) %>%
ggplot( aes(x = mean, y = lang_bias, 
            group = sex, color = sex, shape = type2)) + 
  geom_point() +
  geom_smooth(method = "lm") +
  facet_grid(.~type2 + type, scales = "free_x", drop = T) +
  theme_bw()
```

```{r, fig.width = 10}
d %>%
  group_by(type, sex) %>%
  do(tidy(cor.test(.$mean, .$lang_bias))) %>%
  arrange(p.value) %>%
  select(-parameter, -method, -alternative) %>%
  kable()
```

