---
title: IAT LANG - gender-genius
subtitle: 
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    number_sections: no
    toc: yes
---
  
******

```{r setup, include = F}
rm(list = ls())

# load packages
library(knitr)
library(rmarkdown)
library(tidyverse)
library(langcog)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F, cache = F)
```

## Language data
```{r}
IAT_lang_full_path <- "genius_effect_sizes_google_full.csv"
IAT_lang_restricted_path <- "genius_effect_sizes_google_restricted.csv"
IAT_lang_restricted_path2 <- "genius_effect_sizes_google_restricted2.csv"
lang_key <- read_tsv("language_name_to_google.csv")
```

Let's look at the effect sizes for the restriced vs. full word lists. They're highly correlated. Let's stick with restricted.
```{r}
## Full
IAT_lang_full_raw <- read_csv(IAT_lang_full_path, 
                          col_names = c("language_code", "test",
                                        "bias_type", "effect_size_full")) 
IAT_lang_full <- IAT_lang_full_raw %>%
  add_row(language_code = "hiur", 
          test = "genius_gender", 
          bias_type = "genius_gender", 
          effect_size_full = mean(filter(IAT_lang_full_raw,
                                         language_code %in% c("hi", "ur")) %>% 
                                    pull(effect_size_full))) %>%
    filter(!(language_code %in% c("hi", "ur")))

## Restricted
IAT_lang_raw1 <- read_csv(IAT_lang_restricted_path,
                                col_names = c("language_code", "test",
                                              "bias_type",
                                              "effect_size_restricted"))


IAT_lang_raw2 <- read_csv(IAT_lang_restricted_path2, 
                          col_names = c("language_code", "test",
                                        "bias_type", "effect_size_restricted")) 

IAT_lang_restricted_raw <- bind_rows(IAT_lang_raw1, IAT_lang_raw2)

IAT_lang_restricted <- IAT_lang_restricted_raw %>%
  add_row(language_code = "hiur", 
          test = "genius_gender", 
          bias_type = "genius_gender", 
          effect_size_restricted = mean(filter(IAT_lang_restricted_raw,
                                         language_code %in% c("hi", "ur")) %>% 
                                    pull(effect_size_restricted))) %>%
  filter(!(language_code %in% c("ur")))
```

```{r}
all_es <- left_join(IAT_lang_full %>% select(language_code, effect_size_full),
          IAT_lang_restricted %>% select(language_code, effect_size_restricted)) %>%
  distinct() 

ggplot(all_es,aes(x = effect_size_restricted, y = effect_size_full)) +
  geom_label(aes(label = language_code, color = language_code)) +
  geom_smooth(method = "lm") +
  geom_hline(aes(yintercept = 0), linetype = 2) +
  theme_classic() +
  theme(legend.position = "none")
```

## Behavioral data
```{r}
IAT_behavioral_path <-"../../data/IAT/Gender-Genius/InternationalIAT_LanguageData.csv"

IAT_behavioral_path_raw <- read_csv(IAT_behavioral_path)

IAT_behavioral_tidy <- IAT_behavioral_path_raw %>%
  mutate(lang1 = tolower(PrimaryLanguage),
         lang2 = tolower(lang_other_clean),
         Gender = tolower(Gender),
         subid = 1:n())  %>%
  rename(iat_score = IATScore2, 
         gender = Gender,
         age = Age,
         country = Country) %>%
  mutate(lang = ifelse(lang1 == "other", lang2, lang1)) %>%
  select(subid, iat_score, lang, gender, age, country)  %>%
  left_join(lang_key %>% select(language_code, lang)) %>%
  mutate(region = as.factor(countrycode::countrycode(country, "country.name", "region")))

NSDS <- 40

IAT_behavioral <-   IAT_behavioral_tidy %>%
 filter(iat_score < mean(IAT_behavioral_tidy$iat_score) + (NSDS*sd(IAT_behavioral_tidy$iat_score)),
         iat_score > mean(IAT_behavioral_tidy$iat_score) - (NSDS*sd(IAT_behavioral_tidy$iat_score))) 
```

### By language
Subset to only those languages that have lots of speakers
```{r}
lang_counts <- count(IAT_behavioral, lang)
lang_counts %>%
  arrange(-n) %>%
  DT::datatable()

MINPARTICIPANTS <- 10

targ_langs <- lang_counts %>%
  filter(n >= MINPARTICIPANTS) %>%
  pull(lang)

IAT_behavioral_tidy <- IAT_behavioral  %>%
  filter(lang %in% targ_langs) %>%
  mutate(subid = as.factor(subid))
```

Get mean iat score by language
```{r}
behavioral_means_tidy <- IAT_behavioral_tidy %>%
  group_by(lang) %>%
  multi_boot_standard(col = "iat_score") %>%
  ungroup()  %>%
  rename(behavioral_mean = mean,
         behavioral_ci_lower = ci_lower,
         behavioral_ci_upper = ci_upper)  %>%
  left_join(lang_key %>% select(language_code, lang))

sample_sizes <- count(IAT_behavioral_tidy, lang) %>%
    left_join(lang_key %>% select(language_code, lang))


full_df <- behavioral_means_tidy %>%
  left_join(IAT_lang_restricted, by = "language_code") %>%
  left_join(sample_sizes, by = "language_code") 
```


```{r}
ggplot(full_df, aes(x = effect_size_restricted, y = behavioral_mean)) +
  geom_point(aes( color = language_code, size = log(n))) +
   geom_text(aes(label = language_code)) +
  geom_smooth(method = "lm") +
  geom_hline(aes(yintercept = 0), linetype = 2) +
  theme_classic() +
  theme(legend.position = "none")
```

Stats
```{r}

cor.test(full_df$behavioral_mean, 
                full_df$effect_size_restricted)

weights::wtd.cor(full_df$behavioral_mean, 
                full_df$effect_size_restricted, 
                weight = log(full_df$n), 
                collapse = FALSE)
```



### By language2

Get mean iat score by language
```{r}
behavioral_means_tidy <- IAT_behavioral %>%
  mutate(subid = as.factor(subid)) %>%
  group_by(lang) %>%
  multi_boot_standard(col = "iat_score") %>%
  ungroup()  %>%
  rename(behavioral_mean = mean,
         behavioral_ci_lower = ci_lower,
         behavioral_ci_upper = ci_upper) %>%
  left_join(lang_key %>% select(lang, google_language_code, language_code))

sample_sizes <- count(IAT_behavioral, lang) %>%
  left_join(lang_key %>% select(lang, google_language_code, language_code))

full_df <- behavioral_means_tidy %>%
  left_join(IAT_lang_restricted, by = "language_code") %>%
  left_join(sample_sizes, by = "language_code") 
```


```{r}
ggplot(full_df, aes(x = effect_size_restricted, y = behavioral_mean)) +
  geom_point(aes( color = language_code, size = log(n))) +
   geom_text(aes(label = language_code)) +
  geom_smooth(method = "lm") +
  geom_hline(aes(yintercept = 0), linetype = 2) +
  theme_classic() +
  theme(legend.position = "none")
```

Stats
```{r}

cor.test(full_df$behavioral_mean, 
                full_df$effect_size_restricted)

weights::wtd.cor(full_df$behavioral_mean, 
                full_df$effect_size_restricted, 
                weight = full_df$n, 
                collapse = FALSE)


```


### By language + country
```{r}
behavioral_means_lc <- IAT_behavioral  %>%
    left_join(lang_key)   %>%
    group_by(language_code, region) %>%
    summarize(n = n(),
              behavioral_mean = mean(iat_score))  

full_df2 <- left_join(behavioral_means_lc, IAT_lang_restricted) %>%
  filter(!is.na(effect_size_restricted))

```

Plot
```{r}
ggplot(full_df2, aes(x = effect_size_restricted, 
                     y = behavioral_mean, weight = log(n))) +
  geom_point(aes( color = language_code, size = log(n))) +
  geom_text(aes(label = language_code)) +
  geom_smooth(method = "lm") +
  geom_hline(aes(yintercept = 0), linetype = 2) +
  theme_classic() +
  theme(legend.position = "none")
```

Stats
```{r}
lm(behavioral_mean~effect_size_restricted , full_df2) %>%
  summary()

lme4::lmer(behavioral_mean~effect_size_restricted  + (1|language_code) + (1|region) ,full_df2) %>%
  summary()

weights::wtd.cor(full_df2$behavioral_mean, 
                full_df2$effect_size_restricted, 
                weight = log(full_df2$n), 
                collapse = FALSE)
```

### By participant
```{r}
by_participant_df <-  IAT_behavioral  %>%
  left_join(lang_key)   %>%
  filter(!is.na(language_code)) %>%
  left_join(IAT_lang_restricted, by = "language_code") %>%
  mutate_if(is.numeric, scale)

lme4::lmer(iat_score~effect_size_restricted +  (1|region) + (1|lang),by_participant_df) %>%
  summary()

lme4::lmer(iat_score~effect_size_restricted  + (1|region) +   (1|age) + (1|lang) + (1|gender),by_participant_df) %>%
  summary()

ggplot(by_participant_df, aes(x = effect_size_restricted, 
                     y = iat_score)) +
  geom_point(aes( color = language_code)) +
  geom_smooth(method = "lm") +
  geom_hline(aes(yintercept = 0), linetype = 2) +
  theme_classic() +
  theme(legend.position = "none")

targ_langs <- lang_counts %>%
  filter(n >= 8) %>%
  pull(lang)

lme4::lmer(iat_score~effect_size_restricted*gender + age +(1|country)  + (1|region) +  (1|lang) ,by_participant_df %>% filter(lang %in% targ_langs)) %>%
  summary()

lme4::lmer(iat_score~effect_size_restricted*gender + age + (1|country) +  (1|lang) ,by_participant_df %>% filter(lang %in% targ_langs)) %>%
  summary()

lme4::lmer(iat_score~effect_size_restricted*gender  +age + (1|country) +  (country|region) + (1|lang) ,by_participant_df %>% filter(lang %in% targ_langs)) %>%
  summary()

lme4::lmer(iat_score~effect_size_restricted*gender  +age +  (1|region) + (1|lang) ,by_participant_df %>% filter(lang %in% targ_langs)) %>%
  summary()
```


