## get age residuals for country with large min number of participant value

# load packages
library(knitr)
library(rmarkdown)
library(tidyverse)
library(langcog)
library(stringr)
library(forcats)
library(broom)
library(haven)
library(countrycode)
library(feather)
library(lingtypology)



MIN_PARTICIPANTS_PER_COUNTRY <- 100


```{r}
#d <- read_sav("../data/IAT/Gender-Career/Gender-Career IAT.public.2005-2016.sav") 
#write_feather(d, "../data/IAT/Gender-Career/Gender-Career IAT.public.2005-2016.feather") %>%

d_raw <- read_feather("../../../data/IAT/Gender-Career/Gender-Career\ IAT.public.2005-2016.feather") %>%
  select(D_biep.Male_Career_all, sex, age, countryres, PCT_error_3467, 
         Mn_RT_all_3467, Mn_RT_all_3, Mn_RT_all_4, Mn_RT_all_6, Mn_RT_all_7,
         assocareer, assofamily, impcareer, impfamily, actualduties, idealduties, femaleceos)

d <- d_raw %>%
  filter(PCT_error_3467 <= 25,
         Mn_RT_all_3467 <= 1500,
         Mn_RT_all_3 <= 1800,
         Mn_RT_all_4 <= 1800,
         Mn_RT_all_6 <= 1800,
         Mn_RT_all_7 <= 1800) %>%
    filter(sex %in% c("f", "m")) %>%
    filter(!is.na(D_biep.Male_Career_all) & !is.na(countryres)) %>%
    rename(overall_iat_score = D_biep.Male_Career_all) 


countries <- rev(sort(unique(d$countryres)))[1:233]

d_clean <- d %>% 
  mutate(countryres = as.factor(countryres)) %>%
  filter(countryres %in% countries) %>%
  mutate(country_name = countrycode(countryres,
                                    "iso2c",
                                    "country.name")) %>%
  mutate(country_name = replace(country_name, 
                                countryres == "UK", "UK")) 

country_ns <- count(d_clean, countryres)  %>%
  filter(n >= MIN_PARTICIPANTS_PER_COUNTRY) %>%
  arrange(-n)

d_clean_frequent <- d_clean %>%
  inner_join(country_ns) %>%
  filter(!is.na(country_name))


country_means_career <- d_clean_frequent %>%
  group_by(country_name) %>%
  do(tidy(lm(overall_iat_score ~ age + sex, d = .)))  %>%
  mutate(ci_lower = estimate - (1.96*std.error),
         ci_upper = estimate + (1.96*std.error))

country_means_career_complete <- country_means_career %>%
  mutate(country_code = countrycode(country_name,  "country.name", "iso2c"),
         language_name = unlist(lang.country(country_name, list = T, official = T))[1],
         language_iso = iso.lang(language_name))
country_means_career_complete %>%
filter(is.na(language_name)) %>% 
  as.data.frame() %>%
  distinct(country_name)




write_csv(country_means_career, "iat_behavior_measures_large.csv")
