---
title: Get human iat correlations - Europarl
author: Molly Lewis 
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    theme: cerulean
    code_folding: hide
---

```{r setup, include = F}

# load packages
library(knitr)
library(rmarkdown)
library(tidyverse) 
library(broom)
library(here)
library(data.table)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F, cache = F)

```

```{r}
behavioral_data <- read_csv("/Users/mollylewis/Documents/research/Projects/1_in_progress/IATLANG/data/study0/processed/by_language_df.csv")

europarl_data <-  read_csv(here("exploratory_studies/13_europarl/get_iat_bias/iat_es_lang.csv"))

all_df = europarl_data %>%
  left_join(behavioral_data, by = c("language_code" = "wiki_language_code")) %>%
  select(language_code, lang_es_europarl, es_iat_sex_age_order_implicit_resid,  median_country_age)

ggplot(all_df, aes(x = lang_es_europarl, y = es_iat_sex_age_order_implicit_resid)) +
  geom_text(aes(label = language_code)) +
  geom_smooth(method = "lm")
 

lm(es_iat_sex_age_order_implicit_resid ~ lang_es_europarl + median_country_age, data = all_df) %>%
  summary()

```