---
title: Continuous grammatical gender vs. behavioral bias
subtitle: 
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    number_sections: no
    toc: yes
---
  
******

```{r setup, include = F}
# load packages
library(knitr)
library(rmarkdown)
library(tidyverse)
library(langcog)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F, cache = F)
```

Compare continous measure to binary measure
```{r}
binary_gender <- read_csv("gender_grammar.csv")  %>%
  select(language_name, wikipedia_grammar_type)
binary_gender[binary_gender$language_name == "spanish; castilian", "language_name"] <- "spanish"
binary_gender[binary_gender$language_name ==  "dutch; flemish", "language_name"] <- "dutch"


continuous_gender <- read_csv("continuous_gender.csv")  

all_gender <- left_join(continuous_gender, 
                        binary_gender, by = c("language" = "language_name")) 

```

```{r, include = F}
count(all_gender, num_dif_trans, wikipedia_grammar_type) %>%
  rename(number_diff_translations = n) %>%
  kable()
```


Compare continous gender measure to behavioral measure

```{r}
behavioral <- read_csv("/Users/mollylewis/Documents/research/Projects/1_in_progress/IATLANG/exploratory_analyses/7_age_controls/by_language_df.csv") %>%
  mutate(language_name = tolower(language_name)) %>%
  select(language_name, es_behavioral_iat_resid_simple, es_behavioral_explicit_resid_simple, ggi, wps) %>%
  rename(language = language_name)

full_df <- full_join(behavioral, all_gender) %>%
  data.frame()

ggplot(full_df , aes(y = es_behavioral_iat_resid_simple, x = num_dif_trans)) +
  geom_label(aes(label= language)) +
  geom_smooth(method = "lm") +
  theme_classic()
```

```{r}

binary_df <- full_df %>%
  mutate(empirical_binary = ifelse(num_dif_trans > 0, "gendered", "not_gendered")) %>%
  filter(!is.na(num_dif_trans),
         !is.na(es_behavioral_iat_resid_simple)) 

count(binary_df, empirical_binary, wikipedia_grammar_type) %>%
  kable()

t.test(binary_df[binary_df$empirical_binary == "gendered", "es_behavioral_iat_resid_simple"],
       binary_df[binary_df$empirical_binary != "gendered", "es_behavioral_iat_resid_simple"],
       paired = F)

lm(num_dif_trans ~ es_behavioral_iat_resid_simple, binary_df) %>%
  summary()

lm(num_dif_trans ~ es_behavioral_explicit_resid_simple, binary_df) %>%
  summary()


binary_df %>%
  group_by(empirical_binary) %>%
  multi_boot_standard(col = "es_behavioral_iat_resid_simple", 
                      na.rm = T) %>%
  ggplot(aes(x = empirical_binary, y = mean)) +
  ylab("age-residualized behavioral IAT") +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper))+
  theme_classic()
```

```{r}
binary_df %>%
  group_by(empirical_binary) %>%
  multi_boot_standard(col = "ggi", 
                      na.rm = T) %>%
  ggplot(aes(x = empirical_binary, y = mean)) +
  ylab("ggi") +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper))+
  theme_classic()
```

```{r}
t.test(binary_df[binary_df$empirical_binary == "gendered", "es_behavioral_explicit_resid_simple"],
       binary_df[binary_df$empirical_binary != "gendered", "es_behavioral_explicit_resid_simple"],
       paired = F)

binary_df %>%
  group_by(empirical_binary) %>%
  multi_boot_standard(col = "es_behavioral_explicit_resid_simple", 
                      na.rm = T) %>%
  ggplot(aes(x = empirical_binary, y = mean)) +
  ylab("age-residualized behavioral explicit") +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper))+
  theme_classic()

ggplot(full_df , aes(y = es_behavioral_explicit_resid_simple, x = num_dif_trans)) +
  geom_label(aes(label= language)) +
  geom_smooth(method = "lm") +
  theme_classic()
```
