---
title: Mediation analyses of Study 2 Occupation data
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    number_sections: no
    toc: yes
---
  
******

```{r setup, include = F}
# load packages
library(knitr)
library(rmarkdown)
library(tidyverse)
library(langcog)
library(here)
library(modelr)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F, cache = F)
```



```{r by_language_data}
# occupation form overlap by language
OCCUPATION_OVERLAP_PATH <- here('data/study2/occupation_gender_scores.csv')
by_lang_scores_tidy <- read_csv(OCCUPATION_OVERLAP_PATH)

# Occupation semantics by language
BY_LANGUAGE_OCCUPATION_PATH  <- here("data/study2/occupation_gender_score_by_language.csv")
occupation_semantics <- read_csv(BY_LANGUAGE_OCCUPATION_PATH) 

# Behavioral IAT by languages measure
BEHAVIORAL_IAT_PATH <- here("data/study0/processed/by_language_df.csv")
iat_behavioral_es <- read_csv(BEHAVIORAL_IAT_PATH) %>%
  rename(language_code = "wiki_language_code") %>%
  select(language_code, median_country_age, 
         prop_male,log_age, es_iat_sex_age_order_explicit_resid,
         es_iat_sex_age_order_implicit_resid, per_women_stem_2012_2017, n_participants)

LANG_IAT_PATH <- here("data/study1b/iat_es_lang.csv")
iat_lang_es <- read_csv(LANG_IAT_PATH)

all_es_tidy2 <- full_join(by_lang_scores_tidy, iat_behavioral_es) %>%
  left_join(iat_lang_es)  %>%
  left_join(occupation_semantics)  %>%
  mutate_if(is.numeric, scale) %>%
  filter(language_code != "zu") %>%
  select(language_code, 
         subt_occu_semantics_fm, 
         wiki_occu_semantics_fm,
         median_country_age, 
         lang_es_wiki,
         lang_es_sub,
         es_iat_sex_age_order_implicit_resid, 
         es_iat_sex_age_order_explicit_resid,
         mean_prop_distinct_occs) 
 #drop_na()
```


### Mediation models
Here are the models for the classic mediation test (subtitle models)

y ~ x
```{r mediation}
lm(es_iat_sex_age_order_implicit_resid ~ mean_prop_distinct_occs, 
  data = all_es_tidy2) %>%
  summary()
```

 m ~ x
```{r}
lm(subt_occu_semantics_fm ~ mean_prop_distinct_occs, 
  data = all_es_tidy2) %>%
  summary()
```

y ~ x + m
```{r}
lm(es_iat_sex_age_order_implicit_resid ~  mean_prop_distinct_occs +
     subt_occu_semantics_fm, 
  data = all_es_tidy2) %>%
  summary()
``` 

### Formal tests of mediation

#### Sobel test
```{r}
multilevel::sobel(pred = all_es_tidy2$mean_prop_distinct_occs, 
      med = all_es_tidy2$subt_occu_semantics_fm,
      out = all_es_tidy2$es_iat_sex_age_order_implicit_resid)
```


#### Bootstrap 
```{r}
library(robmed)

all_es_tidy2 %>%
  fit_mediation(
    x = "mean_prop_distinct_occs",
    y = "es_iat_sex_age_order_implicit_resid",
    m = "subt_occu_semantics_fm") %>%
   test_mediation()
```

With age as a covariate
```{r}
all_es_tidy2 %>%
  fit_mediation(
    x = "mean_prop_distinct_occs",
    y = "es_iat_sex_age_order_implicit_resid",
    m = "subt_occu_semantics_fm",
    covariates = "median_country_age") %>%
   test_mediation()
```


## Wiki models
#### Sobel test
```{r}
all_es_tidy3 <- full_join(by_lang_scores_tidy, iat_behavioral_es) %>%
  left_join(iat_lang_es)  %>%
  left_join(occupation_semantics)  %>%
  mutate_if(is.numeric, scale) %>%
  filter(language_code != "zu")  %>%
  select(wiki_occu_semantics_fm,
         median_country_age, 
         es_iat_sex_age_order_implicit_resid, 
         mean_prop_distinct_occs,
         language_code) 
multilevel::sobel(pred = all_es_tidy3$mean_prop_distinct_occs , 
                  med = all_es_tidy3$wiki_occu_semantics_fm,
                  out = all_es_tidy3$es_iat_sex_age_order_implicit_resid)
```

#### Bootstrap 

Bootstrap mediation models have more power: https://journals.sagepub.com/doi/pdf/10.1111/j.1467-9280.2007.01882.x

```{r}
mediation_model_bootsrapped <- all_es_tidy3 %>%
  fit_mediation(
    x = "mean_prop_distinct_occs",
    y = "es_iat_sex_age_order_implicit_resid",
    m = "wiki_occu_semantics_fm") %>%
   test_mediation()

mediation_model_bootsrapped
p_value(mediation_model_bootsrapped)
```

## Occupation as mediator
```{r}
multilevel::sobel(med = all_es_tidy2$mean_prop_distinct_occs , 
                  pred = all_es_tidy2$subt_occu_semantics_fm,
                  out = all_es_tidy2$es_iat_sex_age_order_implicit_resid)

```

## Additive regression models
```{r}

# wiki
lm(es_iat_sex_age_order_implicit_resid ~ 
     mean_prop_distinct_occs + 
     wiki_occu_semantics_fm +
     median_country_age,
   data = all_es_tidy2) %>%
  summary()

lm(es_iat_sex_age_order_implicit_resid ~ 
     mean_prop_distinct_occs + 
   #  wiki_occu_semantics_fm +  
     median_country_age, 
   data = all_es_tidy2) %>%
  summary()

lm(es_iat_sex_age_order_implicit_resid ~ mean_prop_distinct_occs + 
     lang_es_wiki +  
     median_country_age,
   data = all_es_tidy2) %>%
  summary()

# subt
lm(es_iat_sex_age_order_implicit_resid ~ mean_prop_distinct_occs + 
     subt_occu_semantics_fm +  
     median_country_age, 
   data = all_es_tidy2) %>%
  summary()

lm(es_iat_sex_age_order_implicit_resid~ mean_prop_distinct_occs + 
     lang_es_sub +  
     median_country_age, data = all_es_tidy2) %>%
  summary()

```