---
title: Gender in languages
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    number_sections: no
    toc: yes
---
  
```{r setup, include = F}
rm(list = ls())

# load packages
library(knitr)
library(rmarkdown)
library(tidyverse)
library(langcog)
library(stringr)
library(forcats)
library(broom)
library(lingtypology)
library(knitr)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F, cache = F)
```

WALS:
  - 30a: Number of Genders
  - 31a: Sex-based and Non-sex-based Gender Systems
  - 32a: Systems of Gender Assignment
  - 44a: Gender Distinctions in Independent Personal Pronouns
Autotype:
  gender: Gender: Various aspects of gender distinctions and their reflexes. (https://github.com/autotyp/autotyp-data#the-autotyp-database)
  
  
```{r}
codes <- read_csv( "../data/wals/iso3_to_wals.csv")

d <- read_csv( "../data/other/langs_for_study1.csv") %>%
  mutate(iso3 = iso.lang(language_name)) %>%
  mutate(language_name = tolower(language_name)) %>%
  left_join(codes %>% select(ascii_name, id), by = c("language_name" = "ascii_name")) %>%
  mutate(id = replace(id, iso3 == "rus", "rus"),
         id = replace(id, iso3 == "swe", "swe"),
         id = replace(id, iso3 == "tur", "tur"),
         id = replace(id, language_code == "zh", "mnd"),
         id = replace(id, language_code == "es", "spa"),
         id = replace(id, language_code == "nl", "dut"),
         id = replace(id, language_code == "ar", "arb"),
         iso3 = replace(iso3, language_code == "ar", "arb"),
         iso3 = replace(iso3, language_code == "nl", "nld"),
         iso3 = replace(iso3, language_code == "zh", "cmn"),
         iso3 = replace(iso3, language_code == "es", "spa"),
         iso3 = replace(iso3, language_code == "ms", "zsm"),
         iso3 = replace(iso3, language_code == "fa", "pes")) %>%
  rename(wals_id = "id") %>%
  mutate(glottocode = gltc.iso(iso3))
         

wals_data <- wals.feature(c("30a", "31a", "32a", "44a"))
autotyp_data <- autotyp.feature(c("Gender")) #, "Grammatical_markers", "Agreement"))

langs_with_features <- d %>%
  left_join(wals_data %>% select(-glottocode), by = c("wals_id" = "wals.code")) %>%
  left_join(autotyp_data, by = c("glottocode" = "Glottocode")) %>%
  select(-2, -4:-5, -12, -15, -17, -LID, -longitude, -latitude)

kable(langs_with_features)
```