---
title: IAT top languages and countries
subtitle: 2016 gender data
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    number_sections: no
    toc: yes
---
  
******

```{r setup, include = F}
rm(list = ls())

# load packages
library(knitr)
library(rmarkdown)
library(tidyverse)
library(countrycode)
library(haven)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F, cache = F)
```

Set params
```{r}
MIN_PARTICIPANTS_PER_COUNTRY <- 50
```

## Gender-career

Read in 2016 gender IAT data, and get most frequent languages
```{r}
d <- read_sav("../data/IAT/Gender-Career IAT.public.2016.sav") %>%
  select(D_biep.Male_Career_all, sex, countryres)

countries <- rev(sort(unique(d$countryres)))[1:181]

d_clean <- d %>% 
  filter(!is.na(D_biep.Male_Career_all) & !is.na(countryres)) %>%
  mutate(countryres = as.factor(countryres)) %>%
  filter(countryres %in% countries) %>%
  rename(overall_iat_score = D_biep.Male_Career_all)  %>%
  mutate(country_name = countrycode(countryres,
                                    "iso2c",
                                    "country.name")) %>%
  mutate(country_name = replace(country_name, 
                                countryres == "UK", "UK")) 

country_ns <- count(d_clean, countryres)  %>%
  filter(n >= MIN_PARTICIPANTS_PER_COUNTRY)

country_frequent <- d_clean %>%
  inner_join(country_ns) %>% 
  distinct(countryres, .keep_all = T) %>%
  select(country_name, countryres)
```

Get languages for each country
```{r}
iso_codes <- read_csv("../data/other/iso3_and_1.csv") %>%
  rename(language_name = English)

countries_lang <- read_tsv("../data/other/geo_codes.csv", skip = 50) %>%
  rename(country_code = `#ISO`,
         language = Languages) %>%
  select(country_code, language) %>%
  filter(country_code %in% country_frequent$countryres)  %>%
  separate(language,
           into = c("language_code", "other_langs"), 
                             sep = ",") %>%
  separate(language_code,
           into = c("language_code", "other_langs2"), 
             sep = "-")  %>%
  mutate(language_code=replace(language_code, language_code=="cmn", "zh")) %>%
  mutate(country_name = countrycode(country_code, "iso2c", "country.name")) %>%
  left_join(iso_codes %>% select(alpha2, language_name), 
            by = c("language_code" = "alpha2")) %>%
  select(country_name, language_name, country_code, language_code)

write_csv(countries_lang, "../data/other/countries_lang.csv")

```
